### ISSUE TITLE
Ticker is failing to catch invalid symbol?

### ISSUE THREAD

**Issue by Scoodood** [dpguthrie/yahooquery#268] opened 2024-02-27 17:02 UTC
**Describe the bug**
Ticker is failing to catch invalid symbol.

**To Reproduce**
```python
from yahooquery import Ticker

t = Ticker('appl', validate=True)
print(t.symbols)
print(t.invalid_symbols)
print(t.summary_detail)

>>> ['APPL']
>>> None
>>> {'APPL': 'No fundamentals data found for any of the summaryTypes=summaryDetail'}
```

**Expected behavior**
```python
>>> None
>>> ['APPL']
>>> {'APPL': 'No fundamentals data found for any of the summaryTypes=summaryDetail'}```
```

**Desktop (please complete the following information):**
 - Win11 Pro
 - Python 3.12
 - Chrome Version 122.0.6261.69 (Official Build) (64-bit)

**Comment by dpguthrie** [comment] 2024-02-28 00:29
This is because the symbol is actually being found by YF.

Here's the page (even though there's no info):  https://finance.yahoo.com/quote/APPL?.tsrc=fin-srch

And the request to validate is coming back as true:  https://query2.finance.yahoo.com/v6/finance/quote/validate?symbols=APPL

Closing this as expected behavior given the responses from their API.

**Closed by dpguthrie** 2024-02-28 00:29 UTC
