### ISSUE TITLE
Inconsistent datatype when upgrading from 2.3.0 to 2.3.1

### ISSUE THREAD

**Issue by portefeuille** [dpguthrie/yahooquery#175] opened 2023-04-15 06:59 UTC
With 2.3.0:

```
>>> from yahooquery import Ticker
>>> stock = Ticker('GRVO.PA')
>>> data = stock.history(period='2y', interval='1wk', adj_ohlc=True)
>>> data
                                         open        high         low  volume       close  dividends
symbol  date                                                                                        
GRVO.PA 2021-04-12 00:00:00+02:00  113.506491  121.896102  113.506491    3381  116.961037        0.0
        2021-04-19 00:00:00+02:00  119.428569  121.896101  119.428569    2710  120.909088        0.0
        2021-04-26 00:00:00+02:00  121.402600  121.896106  119.428574    1348  119.428574        0.0
        2021-05-03 00:00:00+02:00  120.415581  122.389607  109.064932    3181  120.415581        0.0
        2021-05-10 00:00:00+02:00  118.441554  121.402593  115.480515    1384  115.974022        0.0
...                                       ...         ...         ...     ...         ...        ...
        2023-03-20 00:00:00+01:00   61.000000   61.799999   58.400002    2556   60.799999        0.0
        2023-03-27 00:00:00+02:00   62.000000   62.200001   41.299999   42187   42.099998        0.0
        2023-04-03 00:00:00+02:00   42.400002   44.200001   41.299999   12226   41.500000        0.0
        2023-04-10 00:00:00+02:00   41.599998   42.000000   38.049999   11544   39.150002        0.0
        2023-04-14 17:35:26+02:00   39.500000   39.700001   38.049999    3906   39.150002        0.0

[106 rows x 6 columns]
>>> lines = data.sort_values('date', ascending=False)
>>> lines
                                         open        high         low  volume       close  dividends
symbol  date                                                                                        
GRVO.PA 2023-04-14 17:35:26+02:00   39.500000   39.700001   38.049999    3906   39.150002        0.0
        2023-04-10 00:00:00+02:00   41.599998   42.000000   38.049999   11544   39.150002        0.0
        2023-04-03 00:00:00+02:00   42.400002   44.200001   41.299999   12226   41.500000        0.0
        2023-03-27 00:00:00+02:00   62.000000   62.200001   41.299999   42187   42.099998        0.0
        2023-03-20 00:00:00+01:00   61.000000   61.799999   58.400002    2556   60.799999        0.0
...                                       ...         ...         ...     ...         ...        ...
        2021-05-10 00:00:00+02:00  118.441554  121.402593  115.480515    1384  115.974022        0.0
        2021-05-03 00:00:00+02:00  120.415581  122.389607  109.064932    3181  120.415581        0.0
        2021-04-26 00:00:00+02:00  121.402600  121.896106  119.428574    1348  119.428574        0.0
        2021-04-19 00:00:00+02:00  119.428569  121.896101  119.428569    2710  120.909088        0.0
        2021-04-12 00:00:00+02:00  113.506491  121.896102  113.506491    3381  116.961037        0.0

[106 rows x 6 columns]
```

With 2.3.1:

```
>>> from yahooquery import Ticker
>>> stock = Ticker('GRVO.PA')
>>> data = stock.history(period='2y', interval='1wk', adj_ohlc=True)
>>> lines = data.sort_values('date', ascending=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/Library/Python/3.9/lib/python/site-packages/pandas/core/frame.py", line 6777, in sort_values
    indexer = nargsort(
  File "/Users/me/Library/Python/3.9/lib/python/site-packages/pandas/core/sorting.py", line 429, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: can't compare datetime.datetime to datetime.date
>>> data
                                         open        high         low  volume       close  dividends
symbol  date                                                                                        
GRVO.PA 2021-04-12                 113.506491  121.896102  113.506491    3381  116.961037        0.0
        2021-04-19                 119.428569  121.896101  119.428569    2710  120.909088        0.0
        2021-04-26                 121.402600  121.896106  119.428574    1348  119.428574        0.0
        2021-05-03                 120.415581  122.389607  109.064932    3181  120.415581        0.0
        2021-05-10                 118.441554  121.402593  115.480515    1384  115.974022        0.0
...                                       ...         ...         ...     ...         ...        ...
        2023-03-20                  61.000000   61.799999   58.400002    2556   60.799999        0.0
        2023-03-27                  62.000000   62.200001   41.299999   42187   42.099998        0.0
        2023-04-03                  42.400002   44.200001   41.299999   12226   41.500000        0.0
        2023-04-10                  41.599998   42.000000   38.049999   11544   39.150002        0.0
        2023-04-14 17:35:26+02:00   39.500000   39.700001   38.049999    3906   39.150002        0.0

[106 rows x 6 columns]
```

**Comment by maread99** [comment] 2023-04-15 12:30
Hi @portefeuille

The 2.3.1 behavior is as intended and as described by the 'Returns' section of the method doc.

During a trading session the 'live indice' indicates the time of the last trade. Indexing in this manner prevents ambiguities as to whether this last indice represents the price of a closed or open session. At some point after the close the last indice will revert to a date (exactly when depends on Yahoo)).

A bug in 2.3.0 resulted in daily data being indexed with timezone aware timestamps (as if it were intraday data) whenever the interval was weekly or monthly. This was fixed by [this PR](https://github.com/dpguthrie/yahooquery/pull/141#issuecomment-1418297468).

For post-processing you might be interested in [market_prices](https://github.com/maread99/market_prices) which sits on top of yahooquery.

**Comment by portefeuille** [comment] 2023-04-15 14:35
Thank you @maread99 

In this case, is it possible, without using an additional package, to sort by date like in my example? I'm not really proficient in Python.

**Comment by maread99** [comment] 2023-04-15 16:00
It's already sorted. If you just want to reverse the DataFrame, as your example above, then the following will do it:
```python
df.iloc[::-1]
```
Alternatively, you could replace the last indice with a date. The **general** problem here (i.e. one of the reasons why `yahooquery` doesn't do this) is that without knowledge of the symbol's trading hours it's not possible to know what date the datetime relates to. Usually it will just be the date component of the datetime, although this won't be the case, for example, during the first hour of trading of an equity in Sydney that opens at 23.00 UTC, or a 24 hour trading symbol that similarly opens late on the day prior to that which the data is associated with. This is one of the reasons that the last indice is a datetime rather than a date - it's not possible to know with any certainty what the date should be. [market_prices](https://github.com/maread99/market_prices) resolves this by getting knowledge of stocks' trading hours via [exchange_calendars](https://github.com/gerrymanoim/exchange_calendars), which it simply asks 'what date corresponds with this datetime'.

If you know that the date will be the date component of the datetime then you could do something like:
```python
df = df.droplevel(0)
last_ts = df.index[-1]
if isinstance(last_ts, datetime.datetime):
    session = last_ts.date()
    if len(df) == 1:
        df.index = pd.Index([session])
    else:
        df.index = df.index[:-1].insert(len(df.index) - 1, session)
```
then just sort it in descending order...
```python
df.sort_index(ascending=False)
```

The above **assumes the DataFrame has data for only one symbol**. If you have more than one then it's a matter of doing it symbol by symbol and then putting it all back together, at which point you're probably better off looking at [market_prices](https://github.com/maread99/market_prices).

**Closed** 2023-04-15 19:19 UTC
